name: number_converter
description: A Flutter app for converting numbers between different number systems.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Additional dependencies can be added here if needed

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
